export const SHOW_LOADER = 'SHOW_LOADER'
export const ADD_NOTE = 'ADD_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const FETCH_NOTE = 'FETCH_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_EDIT_NOTE = 'SET_EDIT_NOTE'
export const UPDATE_STATUS_NODE = 'UPDATE_STATUS_NODE'
